# Generated by Django 4.2.3 on 2023-07-20 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('restaurant_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=30)),
                ('count', models.PositiveIntegerField()),
                ('created_on', models.DateField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.restaurant')),
            ],
        ),
    ]
