# Generated by Django 4.2.3 on 2023-07-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_itemhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemhistory',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
