# Generated by Django 4.2.3 on 2023-07-21 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_itemhistory_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='count',
        ),
    ]
