# Generated by Django 4.2.3 on 2023-07-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_item_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
