# Generated by Django 4.2.3 on 2023-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='current_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
